# Generated by Django 2.2.5 on 2020-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200623_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
